# Generated by Django 4.0.4 on 2022-05-17 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr',
            name='cdate',
            field=models.DateField(default=datetime.date(2022, 5, 17)),
        ),
        migrations.AddField(
            model_name='qr',
            name='ctime',
            field=models.TimeField(default=datetime.datetime(2022, 5, 17, 18, 27, 0, 534829)),
        ),
        migrations.AddField(
            model_name='qr',
            name='no_classes',
            field=models.CharField(default=2, max_length=2),
        ),
    ]
